[package]
name = "ddd_macros"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.94"
syn = "2.0.100"
quote = "1.0.40"

[lib]
proc-macro = true
